version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync "dist/" "s3://$DESTINATION_S3_BUCKET/$CODEBUILD_RESOLVED_SOURCE_VERSION" --delete
cache:
  paths:
    - 'app/node_modules/**/*'
    - '/root/.npm/**/*'
artifacts:
  base-directory: app/dist
  files:
    - "**/*"
