AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  createVacationRequest

  Sample SAM Template for createVacationRequest
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: VacationRequest-tthjzp4lebavxlmqbniom57coi-dev
        EVENT_BUS_NAME: VacationTrackerEvents

Resources:
  CreateVacationRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs14.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateVacationRequestFunction:
    Description: "Create Vacation Request Lambda Function ARN"
    Value: !GetAtt CreateVacationRequestFunction.Arn
  CreateVacationRequestFunctionIamRole:
    Description: "Implicit IAM Role created for Create Vacation Request function"
    Value: !GetAtt CreateVacationRequestFunction.Arn
